### ISSUE TITLE
Compare covid-data for 2 - 5 countries

### ISSUE THREAD

**Issue by Lagbana** [Lagbana/covid19-tracker#19]
- [ ] Create button that executes a comparison of 2 - 5 countries and displays on ( X- Axis) for one selected Covid-Data displayed on (Y-Axis)

**Comment by dustinirving** [comment]
Instead of having a button that switches between a comparative bar graph and a regular one, I was thinking of simply  have another box at the bottom of the page. In the box there will be two dropdowns, one for each country. There will be a button called compare. When the user clicks compare a comparative bar graph will appear.

**Comment by dustinirving** [comment]
There will be no text for the number of cases and etc.
